name: advent_of_code
description: Advent of Code
version: 2.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.5
dependencies:
  equatable: ^2.0.5
  meta: ^1.8.0
